name: causal_experiments
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - pytorch
  - cpuonly
  - jupyter
  - jupyterlab
  - matplotlib
  - scikit-learn
  - seaborn
  - tqdm
  - pip
  - pip:
    - igraph
    - gcastle
    - mamba
