dependencies:
  - python=3.8
  - numpy
  - pytorch
  - jupyter
  - jupyterlab
  - matplotlib
  - scikit-learn
  - seaborn
  - tqdm
  - pip
  - jaxlib=*=cuda*  # wildcard version that includes cuda
  - jax
  - pip:
      - igraph
      - gcastle
      - mamba
