# Configuration for a Deep Ensemble Experiment (Version 1)

# General Experiment Settings
experiment_name: "deep_ensemble_20_runs_20_vars"
random_seed: 42

# Data Generation Settings
data:
  n_vars: 20
  n_observations: 100
  n_ho_observations: 100
  n_intervention_sets: 3
  perc_intervened: 0.1

# Model Architecture
model:
  type: "DenseNonlinearGaussian"
  hidden_layers: [5]
  obs_noise: 0.1
  sig_param: 1.0

# Training Parameters
training:
  n_steps: 2000

# List of Learners to Run (even if it's just one)
learners:
  - name: "Ensemble"
    type: "DeepEnsembleLearner"
    n_ensemble_runs: 20

# Evaluation & Plotting
evaluation:
  metrics: ["eshd", "auroc", "negll_obs", "negll_intrv"]
  n_interv_samples: 1000
  interv_value: 0.0